### PR TITLE
fix dyalizer

### PR DESCRIPTION
**Pull request by yanbussieres**
++ reversed body/headers args to mimic hackney. 

there is almost no diff now 👍

### CODE REVIEW

**Review by leikahing — COMMENTED** [review]
I like the arg ordering switch, but this breaks `dialyzer` for various other things (because every API call so far uses the old ordering), e.g.

```
lib/primetrust/assets/asset.ex:16:call
The function call will not succeed.

PrimeTrust.API.req(:get, <<97, 115, 115, 101, 116, 115>>, <<>>, %{}, _opts :: any())

breaks the contract
(
  method(),
  resource :: String.t(),
  headers :: map(),
  body :: map() | binary(),
  opts :: [any()]
) :: {:ok, map()} | {:error, map()}
```

**Review by leikahing — CHANGES_REQUESTED** [review]
Forgot to mark this as 'request changes' since we should be dialyzer clean.

**Comment by yanbussieres** [comment]
Done! 
Also, I pattern-matched the `defp wrap/2`   function with `<<>>`, pls have a quick look to make sure this is really what you want (an empty map).

**Review by leikahing — APPROVED** [review]
Gonna approve so you can push when ready, though a couple things to resolve...

1. The `prep_data` comment in the review
2. Looks like you need to rebase your branch on `main`? Your commit list now contains my more recent changes to it.

**Pull request merged**
